# -*- python -*-

import lsst.sconsUtils
import glob
import os

# scons steals our environment away, so we have to reinstate it
env = lsst.sconsUtils.env.Clone()
environ = dict((name, os.environ[name]) for name in ("PYTHONPATH", "LD_LIBRARY_PATH",
                                                     "DYLD_LIBRARY_PATH", "PATH"))
env.Append(**environ)
# scons also hacks sys.path, so we need to set PYTHONPATH very explicitly at the start of each command.
python = "PYTHONPATH=%s " % environ["PYTHONPATH"]

defectsDatList = glob.glob("defects/*/defects.dat")
for defectsDat in defectsDatList:
    command = "%s bin/genDefectFits.py hsc/hsc_geom.paf %s --force" % (python, os.path.join("hsc", defectsDat))
    env.AlwaysBuild(env.Command('defectsFits', [], command))

command = "%s bin/genDefectRegistry.py --root hsc/defects" % (python)
registry = env.AlwaysBuild(env.Command("defects/defectRegistry.sqlite3", "defectsFits", command))
