# -*- python -*-
Import("env")
import lsst.SConsUtils as scons

dataDir = scons.ProductDir("obs_test_subaru")
if not dataDir:
    print "Warning: obs_test_subaru is not set up; not running the tests!"
else:    
    import glob
    #
    # Tests
    #
    import lsst.tests
    
    tests = lsst.tests.Control(env, verbose = True)
    tests.run("*.py")
