# -*- python -*-
Import("env")
import lsst.SConsUtils as scons

env.CheckSwig("python", ilang="c++",
              includedProducts="utils daf_base daf_data daf_persistence pex_exceptions pex_logging pex_policy security afw")

env.LoadableModuleIncomplete("_deblenderLib", Split("deblenderLib.i"), LIBS=env.getlibs("meas_deblender"))

