# -*- python -*-

import lsst.sconsUtils
from lsst.utils import getPackageDir
import os

# scons steals our environment away, so we have to reinstate it
env = lsst.sconsUtils.env.Clone()
for name in ("PYTHONPATH", "LD_LIBRARY_PATH",
             "DYLD_LIBRARY_PATH", "PATH"):
    if name in os.environ:
        env.AppendENVPath(name, os.environ[name])

# we may need an explicit library load path specified in the command
libpathstr = lsst.sconsUtils.utils.libraryLoaderEnvironment()

pipe_tasks_dir = getPackageDir('pipe_tasks')
data_dir = getPackageDir('obs_subaru_data')
command = (f"{pipe_tasks_dir}/bin/ingestDefects.py suprimecam/CALIBS/ {data_dir}/suprimecam/defects "+
            "--calib suprimecam/CALIBS --config clobber=True")
commandInst = env.Command('CALIBS/calibRegistry.sqlite3', [], command)
env.Depends(commandInst, lsst.sconsUtils.targets["python"])
