# -*- python -*-
from lsst.sconsUtils import scripts, targets, env

objs = env.SourcesForSharedLibrary(Glob("#src/*.cc"))
targets["lib"].extend(env.SharedLibrary(env["packageName"], objs, LIBS=env.getLibs("self")))
